### ISSUE TITLE
No Time

### ISSUE THREAD

**Issue by ghost** [J-8/ShoppingList_backend#49]
Sorry, guys.
You see and the next 2 weeks too I have so much work to do, that I didn't find th time to help you.
Sorry

**Comment by J-8** [comment]
No worries :) We do this for fun and it should always stay this way!

**Comment by jklmnn** [comment]
I'm sorry that I have to say that I don't have much time left since the semester has started. I might comment on issues/pull request and package a new version when it went to master but I won't write much code anymore. I also can't test the current state in devel, especially the database conversion.
I'll come back later, when time gets more.

**Comment by J-8** [comment]
No worries, same here. :/

**Comment by ghost** [comment]
Ok, guys I think I will find more time.
So I will read back in the code, an then lead the development again.
I think on weekend I will start the pull request from devel to master. So we can push the next version, first I need the go from @J-8 that he is on his way with the app.
@jklmnn then you must update your repository :-)

**Comment by jklmnn** [comment]
Can you please test the database change before pulling? As far as I remember @J-8 created a script that converts the databases.
If that works, I'll update.
Can you also move config.php to config.php.def otherwise we would overwrite the config on update. And also the INSTALL.php needs to be changed. When I deleted my config.php last time, it could not create a new one. We should also fix this (this would happen on a new install with just config.php.def in the directory).

**Comment by the0ne** [comment]
closing the issue as the timeframe is over
